// Generated by gencpp from file kinova_optimization/IKSolution.msg
// DO NOT EDIT!


#ifndef KINOVA_OPTIMIZATION_MESSAGE_IKSOLUTION_H
#define KINOVA_OPTIMIZATION_MESSAGE_IKSOLUTION_H

#include <ros/service_traits.h>


#include <kinova_optimization/IKSolutionRequest.h>
#include <kinova_optimization/IKSolutionResponse.h>


namespace kinova_optimization
{

struct IKSolution
{

typedef IKSolutionRequest Request;
typedef IKSolutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IKSolution
} // namespace kinova_optimization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_optimization::IKSolution > {
  static const char* value()
  {
    return "31ace2d87a66926cb643feb651eb2e0b";
  }

  static const char* value(const ::kinova_optimization::IKSolution&) { return value(); }
};

template<>
struct DataType< ::kinova_optimization::IKSolution > {
  static const char* value()
  {
    return "kinova_optimization/IKSolution";
  }

  static const char* value(const ::kinova_optimization::IKSolution&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_optimization::IKSolutionRequest> should match
// service_traits::MD5Sum< ::kinova_optimization::IKSolution >
template<>
struct MD5Sum< ::kinova_optimization::IKSolutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_optimization::IKSolution >::value();
  }
  static const char* value(const ::kinova_optimization::IKSolutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_optimization::IKSolutionRequest> should match
// service_traits::DataType< ::kinova_optimization::IKSolution >
template<>
struct DataType< ::kinova_optimization::IKSolutionRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_optimization::IKSolution >::value();
  }
  static const char* value(const ::kinova_optimization::IKSolutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_optimization::IKSolutionResponse> should match
// service_traits::MD5Sum< ::kinova_optimization::IKSolution >
template<>
struct MD5Sum< ::kinova_optimization::IKSolutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_optimization::IKSolution >::value();
  }
  static const char* value(const ::kinova_optimization::IKSolutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_optimization::IKSolutionResponse> should match
// service_traits::DataType< ::kinova_optimization::IKSolution >
template<>
struct DataType< ::kinova_optimization::IKSolutionResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_optimization::IKSolution >::value();
  }
  static const char* value(const ::kinova_optimization::IKSolutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_OPTIMIZATION_MESSAGE_IKSOLUTION_H
