// Generated by gencpp from file kinova_optimization/RelaxedIKSolutionRequest.msg
// DO NOT EDIT!


#ifndef KINOVA_OPTIMIZATION_MESSAGE_RELAXEDIKSOLUTIONREQUEST_H
#define KINOVA_OPTIMIZATION_MESSAGE_RELAXEDIKSOLUTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kinova_optimization/EEPoseGoals.h>

namespace kinova_optimization
{
template <class ContainerAllocator>
struct RelaxedIKSolutionRequest_
{
  typedef RelaxedIKSolutionRequest_<ContainerAllocator> Type;

  RelaxedIKSolutionRequest_()
    : ee_pose_goals()  {
    }
  RelaxedIKSolutionRequest_(const ContainerAllocator& _alloc)
    : ee_pose_goals(_alloc)  {
  (void)_alloc;
    }



   typedef  ::kinova_optimization::EEPoseGoals_<ContainerAllocator>  _ee_pose_goals_type;
  _ee_pose_goals_type ee_pose_goals;





  typedef boost::shared_ptr< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RelaxedIKSolutionRequest_

typedef ::kinova_optimization::RelaxedIKSolutionRequest_<std::allocator<void> > RelaxedIKSolutionRequest;

typedef boost::shared_ptr< ::kinova_optimization::RelaxedIKSolutionRequest > RelaxedIKSolutionRequestPtr;
typedef boost::shared_ptr< ::kinova_optimization::RelaxedIKSolutionRequest const> RelaxedIKSolutionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator1> & lhs, const ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ee_pose_goals == rhs.ee_pose_goals;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator1> & lhs, const ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinova_optimization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45aea423fbe1cb2b1ac19f5b07f01c21";
  }

  static const char* value(const ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45aea423fbe1cb2bULL;
  static const uint64_t static_value2 = 0x1ac19f5b07f01c21ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinova_optimization/RelaxedIKSolutionRequest";
  }

  static const char* value(const ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinova_optimization/EEPoseGoals ee_pose_goals\n"
"\n"
"================================================================================\n"
"MSG: kinova_optimization/EEPoseGoals\n"
"std_msgs/Header header\n"
"geometry_msgs/Pose[] ee_poses\n"
"std_msgs/String notes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ee_pose_goals);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelaxedIKSolutionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinova_optimization::RelaxedIKSolutionRequest_<ContainerAllocator>& v)
  {
    s << indent << "ee_pose_goals: ";
    s << std::endl;
    Printer< ::kinova_optimization::EEPoseGoals_<ContainerAllocator> >::stream(s, indent + "  ", v.ee_pose_goals);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVA_OPTIMIZATION_MESSAGE_RELAXEDIKSOLUTIONREQUEST_H
