// Generated by gencpp from file kinova_optimization/SelfCollisionQuery.msg
// DO NOT EDIT!


#ifndef KINOVA_OPTIMIZATION_MESSAGE_SELFCOLLISIONQUERY_H
#define KINOVA_OPTIMIZATION_MESSAGE_SELFCOLLISIONQUERY_H

#include <ros/service_traits.h>


#include <kinova_optimization/SelfCollisionQueryRequest.h>
#include <kinova_optimization/SelfCollisionQueryResponse.h>


namespace kinova_optimization
{

struct SelfCollisionQuery
{

typedef SelfCollisionQueryRequest Request;
typedef SelfCollisionQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SelfCollisionQuery
} // namespace kinova_optimization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinova_optimization::SelfCollisionQuery > {
  static const char* value()
  {
    return "8c05d24c55da04c87f44aab507c5f376";
  }

  static const char* value(const ::kinova_optimization::SelfCollisionQuery&) { return value(); }
};

template<>
struct DataType< ::kinova_optimization::SelfCollisionQuery > {
  static const char* value()
  {
    return "kinova_optimization/SelfCollisionQuery";
  }

  static const char* value(const ::kinova_optimization::SelfCollisionQuery&) { return value(); }
};


// service_traits::MD5Sum< ::kinova_optimization::SelfCollisionQueryRequest> should match
// service_traits::MD5Sum< ::kinova_optimization::SelfCollisionQuery >
template<>
struct MD5Sum< ::kinova_optimization::SelfCollisionQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_optimization::SelfCollisionQuery >::value();
  }
  static const char* value(const ::kinova_optimization::SelfCollisionQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_optimization::SelfCollisionQueryRequest> should match
// service_traits::DataType< ::kinova_optimization::SelfCollisionQuery >
template<>
struct DataType< ::kinova_optimization::SelfCollisionQueryRequest>
{
  static const char* value()
  {
    return DataType< ::kinova_optimization::SelfCollisionQuery >::value();
  }
  static const char* value(const ::kinova_optimization::SelfCollisionQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinova_optimization::SelfCollisionQueryResponse> should match
// service_traits::MD5Sum< ::kinova_optimization::SelfCollisionQuery >
template<>
struct MD5Sum< ::kinova_optimization::SelfCollisionQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinova_optimization::SelfCollisionQuery >::value();
  }
  static const char* value(const ::kinova_optimization::SelfCollisionQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinova_optimization::SelfCollisionQueryResponse> should match
// service_traits::DataType< ::kinova_optimization::SelfCollisionQuery >
template<>
struct DataType< ::kinova_optimization::SelfCollisionQueryResponse>
{
  static const char* value()
  {
    return DataType< ::kinova_optimization::SelfCollisionQuery >::value();
  }
  static const char* value(const ::kinova_optimization::SelfCollisionQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVA_OPTIMIZATION_MESSAGE_SELFCOLLISIONQUERY_H
