// Generated by gencpp from file kinova_optimization/SelfCollisionQueryRequest.msg
// DO NOT EDIT!


#ifndef KINOVA_OPTIMIZATION_MESSAGE_SELFCOLLISIONQUERYREQUEST_H
#define KINOVA_OPTIMIZATION_MESSAGE_SELFCOLLISIONQUERYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kinova_optimization/JointAngles.h>

namespace kinova_optimization
{
template <class ContainerAllocator>
struct SelfCollisionQueryRequest_
{
  typedef SelfCollisionQueryRequest_<ContainerAllocator> Type;

  SelfCollisionQueryRequest_()
    : query_state()  {
    }
  SelfCollisionQueryRequest_(const ContainerAllocator& _alloc)
    : query_state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::kinova_optimization::JointAngles_<ContainerAllocator>  _query_state_type;
  _query_state_type query_state;





  typedef boost::shared_ptr< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SelfCollisionQueryRequest_

typedef ::kinova_optimization::SelfCollisionQueryRequest_<std::allocator<void> > SelfCollisionQueryRequest;

typedef boost::shared_ptr< ::kinova_optimization::SelfCollisionQueryRequest > SelfCollisionQueryRequestPtr;
typedef boost::shared_ptr< ::kinova_optimization::SelfCollisionQueryRequest const> SelfCollisionQueryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator1> & lhs, const ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.query_state == rhs.query_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator1> & lhs, const ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinova_optimization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13fb5df8cdc14ce9e1b1635f43f500a7";
  }

  static const char* value(const ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13fb5df8cdc14ce9ULL;
  static const uint64_t static_value2 = 0xe1b1635f43f500a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinova_optimization/SelfCollisionQueryRequest";
  }

  static const char* value(const ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinova_optimization/JointAngles query_state\n"
"\n"
"================================================================================\n"
"MSG: kinova_optimization/JointAngles\n"
"std_msgs/Header header\n"
"std_msgs/Float64MultiArray angles\n"
"std_msgs/String notes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float64[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.query_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SelfCollisionQueryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinova_optimization::SelfCollisionQueryRequest_<ContainerAllocator>& v)
  {
    s << indent << "query_state: ";
    s << std::endl;
    Printer< ::kinova_optimization::JointAngles_<ContainerAllocator> >::stream(s, indent + "  ", v.query_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVA_OPTIMIZATION_MESSAGE_SELFCOLLISIONQUERYREQUEST_H
